apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: Digital_Ocean_Cluster-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: Digital_Ocean_Cluster-cr
subjects:
- kind: ServiceAccount
  name: Digital_Ocean_Cluster-sa
  namespace: default
