apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: Digital_Ocean_Cluster-cr
rules:
- apiGroups:
  - anutosh491.dev
  resources:
  - Digital_Ocean_Clusters
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - anutosh491.dev
  resources:
  - Digital_Ocean_Clusters/status
  verbs:
  - update
- apiGroups:
  - anutosh491.dev
  resources:
  - Digital_Ocean_Clusters
  verbs:
  - get
